### ISSUE TITLE
Switchboard launch checklist

### ISSUE THREAD

**Issue by Cian911** [Cian911/switchboard#10]
- [ ] Add COC readme
- [ ] Add Contributing guidelines
- [ ] Add more examples
- [ ] Launch website
- [ ] Add E2E tests for 3 os arches + have them green
- [ ] Update video on homepage and site
